"""empty message

Revision ID: f5de0343538f
Revises: 
Create Date: 2019-07-01 09:04:36.856091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5de0343538f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classify',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('mycount', sa.Integer(), nullable=True),
    sa.Column('another_name', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('another_name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('passwd', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('article',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('context', sa.String(length=5000), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('tag', sa.String(length=50), nullable=True),
    sa.Column('press', sa.Integer(), nullable=True),
    sa.Column('myclassify', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['myclassify'], ['classify.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('mypress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.String(length=1000), nullable=True),
    sa.Column('articles', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['articles'], ['article.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mypress')
    op.drop_table('article')
    op.drop_table('user')
    op.drop_table('classify')
    # ### end Alembic commands ###
